dict = {'KyalovYV':"@Kyalidis",
        'UshkovaES':"@UshkovaElena",
        'MorozovaEA':"@Moreli96",
        'AlyamovskiyAA':"@alyamovskijAA",
        'ChechetkinaAV':"@ArinaChechetkina",
        'GilevAP':"@Smiiiita",
        'GudkovGK':"@Georgiy_Gudkov",
        'LuchnikovDI':"@Melogor",
        'MaksimovVM':"@MaksimovVM",
        'MikovaDI':"@diamikova",
        'OstaninaAM':"@OstNastasy",
        'PokholkovAV':"@KrasnOFF_YT",
        'SedovMA':"@mis_sed",
        'ShchukinAV':"@aleeexandr",
        'TrukhachevaEE':"@Elenka_Evgen",
        'VoroninIT':"@jlmdie",
        'StukalinAA':"@anoycy",
        'LamskovDA':'@anoycy'}

print(dict['KyalovYV'])
